version: '3'
services:
  downloader:
    image: node:lts-alpine
    restart: always
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: sh -c "npm i && npm run build && node ./build/index.js"
    ports:
      - '80:3000'